### ISSUE TITLE
Service start failure

### ISSUE THREAD

**Issue by lvbaal** [hakavlad/prelockd#6]
Service start failure

```
prelockd.service - Daemon that prevents eviction of executables/libraries from memory
Loaded: loaded (/usr/lib/systemd/system/prelockd.service; enabled; vendor preset: disabled)
Active: failed (Result: exit-code) since Thu 2020-10-22 12:18:17 BST; 13min left
Docs: https://github.com/hakavlad/prelockd
Main PID: 476 (code=exited, status=217/USER)

Oct 22 12:18:17 lam-T440p systemd[1]: Started Daemon that prevents eviction of executables/libraries from memory.
Oct 22 12:18:17 lam-T440p systemd[476]: prelockd.service: Failed to determine user credentials: No such process
Oct 22 12:18:17 lam-T440p systemd[476]: prelockd.service: Failed at step USER spawning /usr/bin/prelockd: No such process
Oct 22 12:18:17 lam-T440p systemd[1]: prelockd.service: Main process exited, code=exited, status=217/USER
Oct 22 12:18:17 lam-T440p systemd[1]: prelockd.service: Failed with result 'exit-code'.
```
I have delete 'user=prelockd' from /usr/lib/systemd/system/prelockd.service to prevent service start failure.
Awaiting an update of the service.

**Comment by hakavlad** [comment]
Do you use Arch Linux?

Maybe the problem was fixed in PKGSRC: 

https://aur.archlinux.org/cgit/aur.git/commit/?h=prelockd-git&id=177b2c2683b267d26dc06d3906abe1e7de8614ec

The problem is that prelockd user was not created during installation.

**Comment by lvbaal** [comment]
> Do you use Arch Linux?
> 
> Maybe the problem was fixed in PKGSRC:
> 
> https://aur.archlinux.org/cgit/aur.git/commit/?h=prelockd-git&id=177b2c2683b267d26dc06d3906abe1e7de8614ec
> 
> The problem is that prelockd user was not created during installation. The problem should be fixed in new installations.

Yes, I'm on arch.
I'm not sure what you mean by "in a new installation" though;
on my system prelockd package is included in [this](https://aur.archlinux.org/packages/performance-tweaks/) package.
Re-installing this package performance-tweaks at this moment does not create the user.
What should I do?

**Comment by ngargg** [comment]
`The problem is that prelockd user was not created during installation. The problem should be fixed in new installations.`
Please tell me when was it fixed. It would be helpful (for Arch)

**Comment by hakavlad** [comment]
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=prelockd-git

I cannot see any fixes.  @librewish Could you comment this, please?

**Comment by hakavlad** [comment]
https://aur.archlinux.org/cgit/aur.git/tree/prelockd.install?h=prelockd-git&id=177b2c2683b267d26dc06d3906abe1e7de8614ec

>when was it fixed

2020-10-22 19:55:41 +0530 

https://aur.archlinux.org/cgit/aur.git/commit/?h=prelockd-git&id=177b2c2683b267d26dc06d3906abe1e7de8614ec

**Comment by librewish** [comment]
Reinstall both 
prelockd-git

And
memavaild-git 

Package as they are fixed by adding an . install file in package which creates users after installation 
but you need to reinstall them to get the fixes.


Or @hakavlad 
Could add a extra commits to the repos so they can get updated automatically

**Comment by lvbaal** [comment]
> Reinstall both
> prelockd-git
> 
> And
> memavaild-git
> 
> Package as they are fixed by adding an . install file in package which creates users after installation
> but you need to reinstall them to get the fixes.
> 
> Or @hakavlad
> Could add a extra commits to the repos so they can get updated automatically

Error reinstalling package:```


❯ pacin prelockd-git
warning: prelockd-git-0.8.r3.g8ad80b1-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) prelockd-git-0.8.r3.g8ad80b1-1

Total Installed Size:  0,03 MiB
Net Upgrade Size:      0,00 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                               [--------------------------------------------] 100%
(1/1) checking package integrity                                             [--------------------------------------------] 100%
error: prelockd-git: signature from "Pedro Henrique Lara Campos <root@pedrohlc.com>" is invalid
:: File /var/cache/pacman/pkg/prelockd-git-0.8.r3.g8ad80b1-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] n
error: failed to commit transaction (invalid or corrupted package (PGP signature))
Errors occurred, no packages were upgraded.
```

**Comment by librewish** [comment]
Try installing again 

the signature mismatch is due to the package was rebuilt

**Comment by lvbaal** [comment]
Fixed. Thanks
