### ISSUE TITLE
Completely hang and RAM goes 100% when "while true; do tail /dev/zero; done"

### ISSUE THREAD

**Issue by Josh-OS** [hakavlad/prelockd#9]
Hi, I found prelockd enticing that would keep my linux from hanging, but prelockd seems to be not working for me.

I saw in the readme file that I can test if prelockd is working with "while true; do tail /dev/zero; done"

After executing "while true; do tail /dev/zero; done" the RAM was immediately full in system monitor app my whole system hangs and restart is needed.

I've done this:

sudo apt install make fakeroot
git clone https://github.com/hakavlad/prelockd.git && cd prelockd
deb/build.sh
sudo apt install --reinstall ./deb/package.deb

Then started and enable the service

sudo systemctl enable --now prelockd.service

Even after restart when I try to "while true; do tail /dev/zero; done" the whole system hangs again and reboot is required.

This is the result of "sudo journalctl -eu prelockd"

> -- Logs begin at Fri 2021-08-20 20:56:05 PST, end at Mon 2021-09-13 23:37:09 PST. --
Sep 13 14:02:16 uss-enterprise systemd[1]: Started Daemon that locks executables/libraries in memory.
Sep 13 14:02:18 uss-enterprise prelockd[9198]: Starting prelockd with config /etc/prelockd.conf
Sep 13 14:02:18 uss-enterprise prelockd[9198]: currently locked 176.9M, 349 files
Sep 13 14:02:59 uss-enterprise systemd[1]: Stopping Daemon that locks executables/libraries in memory...
Sep 13 14:02:59 uss-enterprise prelockd[9198]: Got signal 15
Sep 13 14:02:59 uss-enterprise prelockd[9198]: Unlocking files and dumping snapshots
Sep 13 14:02:59 uss-enterprise prelockd[9198]: Uptime 42.1s, CPU time 0.22s (user 0.08s, sys 0.14s), avg 0.52%
Sep 13 14:02:59 uss-enterprise prelockd[9198]: Exit.
Sep 13 14:02:59 uss-enterprise systemd[1]: prelockd.service: Succeeded.
Sep 13 14:02:59 uss-enterprise systemd[1]: Stopped Daemon that locks executables/libraries in memory.
-- Reboot --
Sep 13 14:05:23 uss-enterprise systemd[1]: Started Daemon that locks executables/libraries in memory.
Sep 13 14:04:36 uss-enterprise prelockd[984]: Starting prelockd with config /etc/prelockd.conf
Sep 13 14:04:36 uss-enterprise prelockd[984]: currently locked 176.9M, 349 files
-- Reboot --
Sep 13 14:11:18 uss-enterprise systemd[1]: Started Daemon that locks executables/libraries in memory.
Sep 13 14:10:32 uss-enterprise prelockd[893]: Starting prelockd with config /etc/prelockd.conf
Sep 13 14:10:32 uss-enterprise prelockd[893]: currently locked 176.9M, 349 files
Sep 13 14:14:51 uss-enterprise prelockd[893]: currently locked 177.2M, 350 files
Sep 13 14:19:51 uss-enterprise prelockd[893]: currently locked 177.2M, 350 files
Sep 13 14:24:51 uss-enterprise prelockd[893]: currently locked 177.2M, 350 files
-- Reboot --
Sep 13 14:28:00 uss-enterprise systemd[1]: Started Daemon that locks executables/libraries in memory.
Sep 13 14:27:18 uss-enterprise prelockd[918]: Starting prelockd with config /etc/prelockd.conf
Sep 13 14:27:18 uss-enterprise prelockd[918]: currently locked 176.9M, 349 files
Sep 13 14:31:00 uss-enterprise systemd[1]: Stopping Daemon that locks executables/libraries in memory...
Sep 13 14:31:00 uss-enterprise prelockd[918]: [Errno 2] No such file or directory: '/var/lib/prelockd/dump.json'
Sep 13 14:31:00 uss-enterprise prelockd[918]: Got signal 15
Sep 13 14:31:00 uss-enterprise prelockd[918]: Unlocking files and dumping snapshots
Sep 13 14:31:00 uss-enterprise systemd[1]: prelockd.service: Main process exited, code=exited, status=1/FAILURE
Sep 13 14:31:00 uss-enterprise systemd[1]: prelockd.service: Failed with result 'exit-code'.
Sep 13 14:31:00 uss-enterprise systemd[1]: Stopped Daemon that locks executables/libraries in memory.
Sep 13 14:38:07 uss-enterprise systemd[1]: Started Daemon that locks executables/libraries in memory.
Sep 13 14:38:07 uss-enterprise prelockd[13679]: Starting prelockd with config /etc/prelockd.conf
Sep 13 14:38:07 uss-enterprise prelockd[13679]: currently locked 176.9M, 349 files
-- Reboot --
Sep 13 14:41:44 uss-enterprise systemd[1]: Started Daemon that locks executables/libraries in memory.
Sep 13 14:41:52 uss-enterprise prelockd[919]: Starting prelockd with config /etc/prelockd.conf
Sep 13 14:41:52 uss-enterprise prelockd[919]: currently locked 19.0M, 42 files
Sep 13 14:45:35 uss-enterprise prelockd[919]: currently locked 175.8M, 348 files
-- Reboot --
Sep 13 14:55:09 uss-enterprise systemd[1]: Started Daemon that locks executables/libraries in memory.
Sep 13 14:55:19 uss-enterprise prelockd[919]: Starting prelockd with config /etc/prelockd.conf
Sep 13 14:55:19 uss-enterprise prelockd[919]: currently locked 19.0M, 42 files
Sep 13 14:59:02 uss-enterprise prelockd[919]: currently locked 175.8M, 348 files
Sep 13 15:04:03 uss-enterprise prelockd[919]: currently locked 176.9M, 349 files
Sep 13 15:09:04 uss-enterprise prelockd[919]: currently locked 176.9M, 349 files
Sep 13 15:12:52 uss-enterprise systemd[1]: Stopping Daemon that locks executables/libraries in memory...
Sep 13 15:12:52 uss-enterprise prelockd[919]: [Errno 2] No such file or directory: '/var/lib/prelockd/dump.json'
Sep 13 15:12:52 uss-enterprise prelockd[919]: Got signal 15
Sep 13 15:12:52 uss-enterprise prelockd[919]: Unlocking files and dumping snapshots
Sep 13 15:12:52 uss-enterprise systemd[1]: prelockd.service: Main process exited, code=exited, status=1/FAILURE
Sep 13 15:12:52 uss-enterprise systemd[1]: prelockd.service: Failed with result 'exit-code'.
Sep 13 15:12:52 uss-enterprise systemd[1]: Stopped Daemon that locks executables/libraries in memory.
Sep 13 15:14:29 uss-enterprise systemd[1]: Started Daemon that locks executables/libraries in memory.
Sep 13 15:14:29 uss-enterprise prelockd[7724]: Starting prelockd with config /usr/local/etc/prelockd.conf
Sep 13 15:14:29 uss-enterprise prelockd[7724]: currently locked 176.9M, 349 files
-- Reboot --
Sep 13 15:17:53 uss-enterprise systemd[1]: Started Daemon that locks executables/libraries in memory.
Sep 13 15:18:02 uss-enterprise prelockd[911]: Starting prelockd with config /usr/local/etc/prelockd.conf
Sep 13 15:18:02 uss-enterprise prelockd[911]: currently locked 19.0M, 42 files
-- Reboot --
Sep 13 15:23:03 uss-enterprise systemd[1]: Started Daemon that locks executables/libraries in memory.
Sep 13 15:23:13 uss-enterprise prelockd[918]: Starting prelockd with config /usr/local/etc/prelockd.conf
Sep 13 15:23:13 uss-enterprise prelockd[918]: currently locked 19.0M, 42 files
Sep 13 15:26:56 uss-enterprise prelockd[918]: currently locked 176.1M, 349 files
Sep 13 15:31:56 uss-enterprise prelockd[918]: currently locked 176.1M, 349 files
-- Reboot --
Sep 13 15:35:05 uss-enterprise systemd[1]: Started Daemon that locks executables/libraries in memory.
Sep 13 15:35:14 uss-enterprise prelockd[893]: Starting prelockd with config /usr/local/etc/prelockd.conf
Sep 13 15:35:14 uss-enterprise prelockd[893]: currently locked 19.0M, 42 files
Sep 13 15:36:26 uss-enterprise systemd[1]: Stopping Daemon that locks executables/libraries in memory...
Sep 13 15:36:26 uss-enterprise prelockd[893]: [Errno 2] No such file or directory: '/var/lib/prelockd/dump.json'
Sep 13 15:36:26 uss-enterprise prelockd[893]: Got signal 15
Sep 13 15:36:26 uss-enterprise prelockd[893]: Unlocking files and dumping snapshots
Sep 13 15:36:26 uss-enterprise systemd[1]: prelockd.service: Main process exited, code=exited, status=1/FAILURE
Sep 13 15:36:26 uss-enterprise systemd[1]: prelockd.service: Failed with result 'exit-code'.
Sep 13 15:36:26 uss-enterprise systemd[1]: Stopped Daemon that locks executables/libraries in memory.
-- Reboot --

**Comment by hakavlad** [comment]
Do you have swap space?

**Comment by hakavlad** [comment]
Secondly, by default, prelocked does not block libraries of all processes. Look at the config.

**Comment by hakavlad** [comment]
BTW, the better alternative is kernels with le9 patch https://github.com/hakavlad/le9-patch

Demo https://www.youtube.com/watch?v=1ZwzjxCHFyc

**Comment by Josh-OS** [comment]
I have 6GB of HDD Swap

> Secondly, by default, prelockd does not block libraries of all processes. Look at the config.

Do I have to configure prelockd to block libraries of all processes?  Sorry I'm a little bit confused.  also, I've seen in the config file that there are '#' and '@' sign in the beginning of each line, is that normal or should I remove it?  I haven't done any modification in my config file, it is still untouched.

> BTW, the better alternative is kernels with le9 patch https://github.com/hakavlad/le9-patch
> 
> Demo https://www.youtube.com/watch?v=1ZwzjxCHFyc

I am not yet comfortable about replacing kernels, can I still use prelockd without touching the kernel?
Btw I love SuperTuxKart haha!

This is my config file
[mylog.txt](https://github.com/hakavlad/prelockd/files/7161917/mylog.txt)

**Comment by Josh-OS** [comment]
> BTW, the better alternative is kernels with le9 patch https://github.com/hakavlad/le9-patch
> 
> Demo https://www.youtube.com/watch?v=1ZwzjxCHFyc

Watching the demo and reading this blog https://www.phoronix.com/scan.php?page=news_item&px=le9-Linux-Low-RAM
I'm impressed, I hope this will be included in the mainline kernel.

**Comment by Josh-OS** [comment]
I removed the  '#' and '@' in config that is located in /etc/prelockd.conf but it didn't help

**Comment by Josh-OS** [comment]
I've gain enough courage to replace my kernel  (Stock kernel of Pop OS 20.04 LTS) with Xanmod.  I installed it with "sudo apt update && sudo apt install linux-xanmod" (5.13.18-xanmod1).

I also found this: https://forum.xanmod.org/thread-4102.html

The mgLRU is disabled by default

`cat /sys/kernel/mm/lru_gen/enabled` the output is 0

but when I try to "while true; do tail /dev/zero; done", still the same, it hangs my Pop OS to death.  I tried googling things but no solution was found.  Google results doesn't even show hot to enable le9 patch in xanmod and I don't know how to verify if it is enabled or not.

**Comment by hakavlad** [comment]
Run
```
sudo swapoff -a
sudo sysctl vm.clean_min_kbytes=333000
```
and try again.

**Comment by Josh-OS** [comment]
> Run
> 
> ```
> sudo swapoff -a
> sudo sysctl vm.clean_min_kbytes=333000
> ```
> 
> and try again.

It worked! maybe I have to completely disable my swap.
My linux works smoother now and doesn't die when I "while true; do tail /dev/zero; done"
I wan't to keep my swap on  as possible, I may try to set my swappiness to 1 or 0, but if that won't work then I'll just disable the swap. Thanks @hakavlad

**Comment by Josh-OS** [comment]
Did not work with swap, I will now disable swap.
Thanks again :D

**Comment by hakavlad** [comment]
You may use swap on zram.

**Comment by Josh-OS** [comment]
I heard about zram in android forums before but not awere of it, I googled it before trying and I like the idea of using my RAM as a compressed swap, it worked like magic.

So I disabled swap and enabled zram.

I can now watch YouTube while "while true; do tail /dev/zero; done" is running, how amazing is that isn't it?  It's a little laggy when tail is running (just like in the YouTube video -which is understandable) but when I close the terminal running the tail my desktop becomes very smooth instantly.

And we know what it means... smooooth linux haha
Thanks again @hakavlad

**Comment by Josh-OS** [comment]
However after reboot when I try again, it hangs again and unusable.  zram is active and I can see the "kill" in my terminal in tail but it took too long to kill again util my desktop is no longer responding.

swap is off
zram as swap is on

is "sudo sysctl vm.clean_min_kbytes=333000" persistent after reboot or do I have to set it everytime I boot?
I think I have to "sudo sysctl vm.clean_min_kbytes=333000" everytime I reboot because it is not working when I don't, but it works when I do "sudo sysctl vm.clean_min_kbytes=333000"

**Comment by hakavlad** [comment]
add to `/etc/sysctl.conf`
```
vm.clean_min_kbytes = 333000
```
https://man7.org/linux/man-pages/man5/sysctl.conf.5.html

**Comment by Josh-OS** [comment]
Done, it is now working even after restart.  My desktop experience is fast and smoother now
Thanks you sir, maybe I can close this now
